apps/urls.py
from django.conf.urls import include, url
from django.contrib import admin    # enable admin for Django
admin.autodiscover()
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
   url(r'', include('quailapp.urls', namespace="quailapp")),    # allow for more intuitive access to urls in templates
   url(r'^admin/', include(admin.site.urls)),   # include admin link for Django
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

quailapp/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required

from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^index$', login_required(views.index), name='index'),
    #url(r'^get$', login_required(views.get_question), name='get'), # deprecated
    url(r'^(?P<answer_id>[a-zA-Z0-9]+)/deleteans/$', login_required(views.delete_answer), name='deleteans'), # deletes answers assoc w/ question
    url(r'^(?P<question_id>[0-9][a-zA-Z0-9]+)/$', login_required(views.question_detail), name='detail'), # messy solution; question ids too long
    url(r'^(?P<question_id>[a-zA-Z0-9]+)/vote/$', login_required(views.vote), name='vote'), # vote for a specific question
    url(r'^(?P<question_id>[a-zA-Z0-9]+)/star/$', login_required(views.star), name='star'), # star a specific question
    url(r'^(?P<question_id>[a-zA-Z0-9]+)/pin/$', login_required(views.pin), name='pin'), # pin a specific question
    url(r'^(?P<question_id>[a-zA-Z0-9]+)/answer/$', login_required(views.get_answer), name='answer'), # answer a specific question
    url(r'^login$', views.login_CAS, name='login'),
    url(r'^logout$', views.logout_CAS, name='logout'),
    url(r'^(?P<netid>[a-zA-Z0-9]+)/create$', views.create_account, name='create'),
    url(r'^userinfo$', login_required(views.user_info), name='userinfo'),
    url(r'^enroll$', login_required(views.enroll), name='enroll'),
    #url(r'^(?P<course_id>[a-zA-Z0-9]+)/coursepage/$', login_required(views.coursepage), name='coursepage'),
    url(r'^(?P<course_id>[a-zA-Z0-9]+)/coursepage_live/$', login_required(views.coursepage_live), name='coursepage_live'),
    url(r'^(?P<course_id>[a-zA-Z0-9]+)/coursepage_archive/$', login_required(views.coursepage_archive), name='coursepage_archive'),
    url(r'^(?P<question_id>[a-zA-Z0-9]+)/delete_from_coursepage/$', login_required(views.delete_from_coursepage), name='delete_from_coursepage'), # a little hacky.
    url(r'^(?P<tag_id>[a-zA-Z0-9]+)/delete_tag_from_coursepage/$', login_required(views.delete_tag_from_coursepage), name='delete_tag_from_coursepage'), # a little hacky.
    url(r'^(?P<question_id>[a-zA-Z0-9]+)/delete_from_info/$', login_required(views.delete_from_userinfo), name='delete_from_userinfo'),
    url(r'^similar_question$', login_required(views.similar_question), name='similar_question'),
    url(r'^change_name$', login_required(views.change_name), name='change_name'),
    url(r'^(?P<question_id>[a-zA-Z0-9]+)/edit_question/$', login_required(views.edit_question), name='edit_question'),
    url(r'^(?P<question_id>[a-zA-Z0-9]+)/edit_answer/$', login_required(views.edit_answer), name='edit_answer'),
    url(r'^(?P<course_id>[a-zA-Z0-9]+)/answered_questions/$', login_required(views.answered_questions), name='answered_questions'),
    url(r'^(?P<category_id>[a-zA-Z0-9]+)/answered_questions_social/$', login_required(views.answered_questions_social), name='answered_questions_social'),
    url(r'^(?P<course_id>[a-zA-Z0-9]+)/feedback/$', login_required(views.user_feedback), name='user_feedback'),
    url(r'^(?P<feedback_id>[a-zA-Z0-9]+)/feedback/delete$', login_required(views.delete_feedback), name='delete_feedback'),
    url(r'^archived_feedback$', login_required(views.archived_feedback), name='archived_feedback'),
    url(r'^social$', login_required(views.social_home), name='social_home'),
    url(r'^(?P<category_id>[a-zA-Z0-9]+)/social/$', login_required(views.social_category), name='social_category'),
    url(r'^(?P<question_id>[0-9][a-zA-Z0-9]+)/social$', login_required(views.social_detail), name='social_detail'), # messy solution; there CANNOT be a trailing slash, otherwise will confuse w/ social category link
    url(r'^(?P<question_id>[a-zA-Z0-9]+)/delete_from_social/$', login_required(views.delete_from_social), name='delete_from_social'), # a little hacky.
    url(r'^(?P<tag_id>[a-zA-Z0-9]+)/delete_tag_from_social/$', login_required(views.delete_tag_from_social), name='delete_tag_from_social'), # a little hacky.

    #url(r'^class$', views.register_class, name='class'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

quailapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
import sys, os, cgi, urllib, re

# Create your models here.

class AllNetids(models.Model):
  all_netids = models.TextField()

class QuailUserManager(BaseUserManager):
  #def create_user(self, netid, first_name, last_name, is_student, courses_by_name=None, password=None):
  def create_user(self, netid, first_name, last_name, is_student, courses_by_id=None, password=None):
    if not netid:
      raise ValueError('User must have netid')
    #new_user = self.model(netid=netid, first_name=first_name, last_name=last_name, is_student=is_student, courses_by_name=courses_by_name)
    new_user = self.model(netid=netid, first_name=first_name, last_name=last_name, is_student=is_student, courses_by_id=courses_by_id)
    new_user.set_password(password)
    new_user.save(using=self._db)
    return new_user

  def create_superuser(self, netid, first_name, last_name, is_student, password):
    user = self.create_user(netid, first_name, last_name, is_student, password=password)
    user.is_admin = True
    user.is_staff = True
    user.save(using=self._db)
    return user

class QuailUser(AbstractBaseUser, PermissionsMixin):
  netid = models.TextField(unique=True)
  first_name = models.TextField()
  last_name = models.TextField()
  is_student = models.BooleanField()
  is_admin = models.BooleanField(default=False)
  is_staff = models.BooleanField(default=False)
  is_active = models.BooleanField(default=True)
  chosen_filter = models.CharField(default='-votes', max_length=10)

  courses_by_id = models.TextField(max_length=10)

  USERNAME_FIELD = 'netid'
  REQUIRED_FIELDS = ['first_name', 'last_name', 'is_student']

  objects = QuailUserManager()

  def get_full_name(self):
    return self.netid

  def get_short_name(self):
    return self.netid

  def __unicode__(self):
    return self.netid

  def has_perm(self, perm, obj=None):
    return True

  def has_module_perms(self, app_label):
    return True

  def course_id_list(self):
    return self.courses_by_id.split('|')

  # def provided_feedback(self):
  #   courses_feedback = {}
  #   course_id_list = self.courses_by_id.split('|')
  #   for courseid in course_id_list:
  #     courses_feedback[str(courseid)] = False
  #   return courses_feedback

  def courses_as_list(self):
    course_list = []
    course_ids = self.courses_by_id.split('|')
    for courseid in course_ids:
      if courseid != '':
        course_list.append(Course.objects.get(courseid=courseid))
    return course_list

class Course(models.Model):
  dept = models.TextField(max_length=3) # new
  num = models.TextField(max_length=3)  # new
  title = models.TextField()  # new
  #name = models.TextField()
  courseid = models.TextField() # new
  professor = models.TextField()
  starttime = models.TimeField(null=False)
  endtime = models.TimeField(null=False)
  days = models.CharField(max_length=10)
  archive_type = models.TextField(default='every_lecture') # allow profs to change how questions are archived
  last_lecture = models.DateField(null=True)

  def days_as_list(self):
    weekdays = []
    for d in self.days:
      if (d == '0'):
        weekdays.append('M')
      elif (d == '1'):
        weekdays.append('T')
      elif (d == '2'):
        weekdays.append('w')
      elif (d == '3'):
        weekdays.append('Th')
      else:
        weekdays.append('F')
    return weekdays

  def days_as_string(self):
    weekdays = ""
    for d in self.days:
      if (d == '0'):
        weekdays += 'M/'
      elif (d == '1'):
        weekdays += 'T/'
      elif (d == '2'):
        weekdays += 'W/'
      elif (d == '3'):
        weekdays += 'Th/'
      else:
        weekdays += 'F/'
    return weekdays[:len(weekdays)-1]

  def __unicode__(self):
    depts = self.dept.split('/')
    nums = self.num.split('/')
    name = ""
    for i in range(len(depts)):
      name += depts[i] + " " + nums[i] + '/'
    name = name[:len(name)-1]
    return '%s: %s' % (name, self.title)  

class ProvidedFeedback(models.Model):
  provided_feedback = models.BooleanField(default=False)
  submitter = models.ForeignKey(QuailUser, null=True)
  course = models.OneToOneField(Course, null=True, on_delete=models.CASCADE)

  def __unicode__(self):
    feedback = '%s for %s: %s' % (self.submitter.netid, self.course, self.provided_feedback)
    return feedback

class Category(models.Model):
  text = models.TextField() # name of the social category

  def __unicode__(self):
    return self.text

class Tag(models.Model):
  text = models.TextField() # the actual tag name itself
  course = models.ForeignKey(Course, null=True) # tags associated with a course
  category = models.ForeignKey(Category, null=True) # tags associated with a course

  questions = models.TextField(default="")  # question ids under this tag
  submitter = models.ForeignKey(QuailUser, null=True)

  def __unicode__(self):
    return self.text

# # allow tags to be associated with social categories
# class SocialTag(models.Model):
#   text = models.TextField() # the actual tag name itself
#   category = models.ForeignKey(Category, null=True) # tags associated with a course
#   questions = models.TextField(default="")  # question ids under this tag
#   submitter = models.ForeignKey(QuailUser, null=True)

class Question(models.Model):
    created_on = models.DateTimeField(auto_now_add=True)
    text = models.TextField()
    votes = models.IntegerField(default=0)
    stars = models.IntegerField(default=0)
    submitter = models.ForeignKey(QuailUser, null=True)
    rank_score = models.FloatField(default=0.0)
    course = models.ForeignKey(Course, null=True)
    is_pinned = models.BooleanField(default=False)
    is_live = models.BooleanField(default=True)
    tags = models.TextField(null=True, default="") # allow tags (separated by '|')
    category = models.ForeignKey(Category, null=True) # allow social categorization
    is_social = models.BooleanField(default=False) # allow social filter

    users_upvoted = models.TextField(null=True, blank=True, default="")
    users_downvoted = models.TextField(null=True, blank=True, default="")
    users_starred = models.TextField(null=True, blank=True, default="")

    class Meta:
      ordering = ['-votes']

    def __unicode__(self):
        return self.text

    def tags_as_list(self):
      tag_list = []
      tag_ids = self.tags.split('|')
      for tag in tag_ids:
        if tag != '':
          tag_list.append(Tag.objects.get(pk=tag))
      return tag_list

class Answer(models.Model):
  created_on = models.DateTimeField(auto_now_add=True) 
  text = models.TextField()
  submitter = models.ForeignKey(QuailUser, null=True)
  question = models.OneToOneField(Question, null=True, on_delete=models.CASCADE)

  def __unicode__(self):
    return self.text

class Comment(models.Model):
  created_on = models.DateTimeField(auto_now_add=True) 
  text = models.TextField()
  submitter = models.ForeignKey(QuailUser, null=True)
  question = models.ForeignKey(Question, null=True, on_delete=models.CASCADE)

  def __unicode__(self):
    return self.text

class Feedback(models.Model):
  created_on = models.DateTimeField(auto_now_add=True) 
  archived_on = models.DateField(null=True)
  text = models.TextField(null=True, blank=True, default="")
  submitter = models.ForeignKey(QuailUser, null=True)
  course = models.ForeignKey(Course, null=True, on_delete=models.CASCADE)
  is_live = models.BooleanField(default=True)
  feedback_choice = models.CharField(max_length=5, null=True)
  lecture_date = models.DateField(null=True)

  class Meta:
      ordering = ['-created_on']

  def __unicode__(self):
    return self.text

# for CAS login..
class CASClient:
   def __init__(self, request):
      self.cas_url = 'https://fed.princeton.edu/cas/'
      self.request = request
   def Authenticate(self):
      # If the request contains a login ticket, try to validate it
      if 'ticket' in self.request.GET:
         netid = self.Validate(self.request.GET['ticket'])
         if netid != None:
            return netid
   

   def redirect_url(self):
      login_url = self.cas_url + 'login' + '?service=' + urllib.quote(self.ServiceURL())
      return login_url
      
   def redirect_url_logout(self):
      logout_url = self.cas_url + 'logout' + '?service=' + urllib.quote(self.ServiceURL_logout())
      return logout_url


   def Validate(self, ticket):
      val_url = self.cas_url + "validate" + \
         '?service=' + urllib.quote(self.ServiceURL()) + \
         '&ticket=' + urllib.quote(ticket)
      r = urllib.urlopen(val_url).readlines()   # returns 2 lines
      if len(r) == 2 and re.match("yes", r[0]) != None:
         return r[1].strip()
      return None

   def ServiceURL_logout(self):
      ret = 'http://' + self.request.META['HTTP_HOST'] + "/"
      ret = re.sub(r'ticket=[^&]*&?', '', ret)
      ret = re.sub(r'\?&?$|&$', '', ret)
      return ret

   def ServiceURL(self):
      ret = 'http://' + self.request.META['HTTP_HOST'] + self.request.META['PATH_INFO']
      ret = re.sub(r'ticket=[^&]*&?', '', ret)
      ret = re.sub(r'\?&?$|&$', '', ret)
      return ret
      #if os.environ.has_key('REQUEST_URI'):
      #   ret = 'http://' + os.environ['HTTP_HOST'] + os.environ['REQUEST_URI']
      #   ret = re.sub(r'ticket=[^&]*&?', '', ret)
      #   ret = re.sub(r'\?&?$|&$', '', ret)
      #   return ret
         #$url = preg_replace('/ticket=[^&]*&?/', '', $url);
         #return preg_replace('/?&?$|&$/', '', $url);
      #return "something is badly wrong"
 
def main():
  print "CASClient does not run standalone"
if __name__ == '__main__':
  main()

quailapp/forms.py
from django import forms
from .models import Course

FEEDBACK_CHOICES = (
    ('1', '1'),
    ('2', '2'),
    ('3', '3'),
    ('4', '4'),
    ('5', '5'),
)

class QuestionForm(forms.Form):
    def __init__(self, *args, **kwargs):
		self.tags = kwargs.pop('tags')
		super(QuestionForm,self).__init__(*args,**kwargs)
		self.fields['your_question'] = forms.CharField(label='Your question', max_length=100)
		self.fields['tags'] = forms.ModelMultipleChoiceField(widget=forms.CheckboxSelectMultiple(), label='', queryset=self.tags, required=False)

class FeedbackForm(forms.Form):
	feedback_choice = forms.ChoiceField(widget=forms.RadioSelect(), label='', choices=FEEDBACK_CHOICES, required=True)
	your_feedback = forms.CharField(label='Your feedback', max_length=200, required=False)

class AnswerForm(forms.Form):
    your_answer = forms.CharField(label='Your answer', max_length=200)

class CommentForm(forms.Form):
    your_comment = forms.CharField(label='Your answer', max_length=300)

class TagForm(forms.Form):
    your_tag = forms.CharField(label='Your tag', max_length=50)

class RegisterForm(forms.Form):
	first_name = forms.CharField(label='First Name:', max_length=100,
		widget=forms.TextInput(attrs={'placeholder': ''}))
	last_name = forms.CharField(label='Last Name:', max_length=100,
		widget=forms.TextInput(attrs={'placeholder': ''}))
	is_student = forms.TypedChoiceField(label='Are you a student?',
		coerce=lambda x: bool(int(x)), choices=[(0,'Lecturer'), (1,'Student')],
		widget=forms.RadioSelect())

class ClassForm(forms.Form):
	your_class = forms.CharField(label='Register class', max_length=50)
	your_professor = forms.CharField(label='Professor', max_length=50)
	start_time = forms.TimeField(label='Start time')
	end_time = forms.TimeField(label='Start time')

class EnrollForm(forms.Form):

	def __init__(self, *args, **kwargs):
		self.courses_available = kwargs.pop('courses_available')
		super(EnrollForm,self).__init__(*args,**kwargs)
		self.fields['courses'] = forms.ModelMultipleChoiceField(widget=forms.CheckboxSelectMultiple(), label='', queryset=self.courses_available)

quailapp/templates/quailapp/archived_feedback.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block classes %}
{% for course in courses %}
<li>
	<a href="{% url 'quailapp:coursepage_live' course.id %}">{{ course }}</a>
</li>
{% endfor %}
{% endblock %}

{% block social %}
{% for category in categories %}
<li>
	<a href="{% url 'quailapp:social_category' category.id %}">{{ category }}</a>
</li>
{% endfor %}
{% endblock %}

{% block content %}
<a href="{% url 'quailapp:index' %}">
{% bootstrap_icon "arrow-left"%} Home
</a>

<h2>Archived Feedback for Lectured Courses</h2>

<h4>Stats</h4>
<span>Total feedback given: {{ total }}</span>
<br>
<span>Score distribution:</span>
<div class="chart">
	{% for percent in percents %}
		{% if not forloop.first %}
  		<div style="width: {{ percent }}%;">{{ forloop.counter0 }}</div> {{ percent }}%
  		<br>
  		{% endif %}
  	{% endfor %}
</div>

{% for course in courses %}
	<h4>{{course}}</h4>
	{% if course.feedback_set.all|length == 0 %}
		N/A<br>
	{% else %}
		{% for feedback in course.feedback_set.all %}
			{% if not feedback.is_live %}
			<li>
				<div class="box-static-gray row">
					<div class="col-xs-1">
						<span>
						{% if not feedback.feedback_choice %}N/A{%else %}{{ feedback.feedback_choice }}/5{% endif %}
						</span>
					</div>
					<div class="col-xs-11">
						<span>
							{% if not feedback.text %}N/A{%else %}{{ feedback }}{% endif %}
						</span>
						<br>
						<span class="unemph">Submitted on: {{ feedback.created_on }}
								for lecture on {{ feedback.lecture_date }}
						</span>
					</div>
				</div>
			</li>
			{% endif %}
		{% endfor %}
	{% endif %}
	<br>
{% endfor %}

{% endblock %}

quailapp/templates/quailapp/enrollform.html
{% load bootstrap3 %}
{% bootstrap_form form %}

quailapp/templates/quailapp/index.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block classes %}
{% for course in courses %}
<li>
	<a href="{% url 'quailapp:coursepage_live' course.id %}">{{ course }}</a>
</li>
{% endfor %}
{% endblock %}

{% block social %}
{% for category in categories %}
<li>
	<a href="{% url 'quailapp:social_category' category.id %}">{{ category }}</a>
</li>
{% endfor %}
{% endblock %}

{% block content %}

<h1 class="centered">Welcome, {{ user.first_name }}</h1>

<div class="row">
	<div class="col-xs-4">
		<div class="box-static-dark">
			<h5 class="centered">
				<a href="{% url 'quailapp:userinfo' %}">
					User info
				</a>
			</h5>
		</div>
		<div class="box-static">
			<span>{{ user.netid }}: {{ user.first_name }} {{ user.last_name }}</span><br>
			<span>Courses enrolled: {{ courses|length }} </span><br>
			<span>Questions asked: {{ user.question_set.all|length }} </span><br>
			<span>Questions answered: {{ user.answer_set.all|length }} </span><br>
			<span>Comments made: {{ user.comment_set.all|length }} </span>
			{% if user.is_student %}
			<br>
			<span>Feedback provided: {{ user.feedback_set.all|length }} </span>
			{% endif %}
		</div>
		<br>
		<div class="box-static-dark">
				<h5 class="centered">Starred questions</h5>
			</a>
		</div>
		<div class="box-static">
			<ul>
			{% for q in starred_questions %}
				{% if q.is_social %}
				<li><a href="{% url 'quailapp:social_detail' q.id %}">{{ q.text }}</a></li>
				{% else %}
				<li><a href="{% url 'quailapp:detail' q.id %}">{{ q.text }}</a></li>
				{% endif %}
			{% endfor %}
			</ul>
		</div>
		<br>

		{% if user.is_student %}
		<div class="box-static-dark">
			<h5 class="centered">
				Feedback
			</h5>
		</div>
		<div class="scrollbox box-static">
			{% for course in courses %}
				<a href="{% url 'quailapp:user_feedback' course.id %}">{{course}}</a>
				<br>
				{% if course.feedback_set.all|length == 0 %}
					None yet!<br>
				{% else %}
					{% for feedback in user.feedback_set.all %}
						{% if feedback.course == course %}
						<li>
							<div class="box-static-dark-padded">
								<span>{% if not feedback.text %}N/A{% else %}{{ feedback }}{% endif %}</span>
								<br>
								<span>Quality of lecture: {% if not feedback.feedback_choice %}N/A{%else %}{{ feedback.feedback_choice }}/5{% endif %}</span>
								<br>
								<span class="unemph">Lecture on {{ feedback.lecture_date }}
								</span>
							</div>
						</li>
						{% endif %}
					{% endfor %}
				{% endif %}
				<br>
			{% endfor %}
		</div>
		{% else %}
		<div class="box-static-dark">
			<h5 class="centered">
				Feedback <a href="{% url 'quailapp:archived_feedback' %}">(archived)</a>
			</h5>
		</div>
		<div class="scrollbox box-static">
			{% for course in courses %}
				<span class="italic">{{course}}</span>
				<br>
				{% if course.feedback_set.all|length == 0 %}
					None yet!<br>
				{% else %}
					{% for feedback in course.feedback_set.all %}
						{% if feedback.is_live %}
						<li>
							<div class="box-static-dark-padded">
							{% if not feedback.text %}N/A{% else %}{{ feedback }}{% endif %}
							<br>
							<span class="bold">Quality of lecture: {% if not feedback.feedback_choice %}N/A{%else %}{{ feedback.feedback_choice }}/5{% endif %}</span><br>
							<span class="unemph">Lecture on {{ feedback.lecture_date }}
							</span>
							<br>
							<small>
								<form action="{% url 'quailapp:index' %}" method="post">
								{% csrf_token %}
						  			<button type="submit" name="feedback" value="{{feedback.id}}" class="btn-link btn-link-gray">Archive</button>
								</form> 
							</small>
							</div>
						</li>
						{% endif %}
					{% endfor %}
				{% endif %}
				<br>
			{% endfor %}
		</div>

		{% endif %}

	</div>
	<div class="col-xs-8">
		{% for course in courses %}
			<div class="box-static-dark">
				<a href="{% url 'quailapp:coursepage_live' course.id %}">
					<h5>{{ course }}</h5>
				</a>
			</div>
			<div class="box-static">
				Professor: {{ course.professor }}<br>
				Class times:
				{{ course.days_as_string }}  {{ course.starttime}} - {{ course.endtime }}
				</a>
			</div>
			<br>
		{% endfor %}
	</div>
</div>

{% endblock %}

quailapp/templates/quailapp/social.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block classes %}
{% for course in courses %}
<li>
	<a href="{% url 'quailapp:coursepage_live' course.id %}">{{ course }}</a>
</li>
{% endfor %}
{% endblock %}

{% block social %}
{% for category in categories %}
<li>
	<a href="{% url 'quailapp:social_category' category.id %}">{{ category }}</a>
</li>
{% endfor %}
{% endblock %}

{% block content %}

<h1 class="centered">Welcome, {{ user.first_name }}</h1>

<div class="row">
	<div class="col-xs-4">
		{% for category in categories %}
			<div class="box-static-dark">
				<a href="{% url 'quailapp:social_category' category.id %}">
					<h5>{{ category }}</h5>
				</a>
			</div>
			<br>
		{% endfor %}
	</div>

	<div class="col-xs-8 box-static-dark">
		<h5 class="centered">
			Recent Questions
		</h5>
	</div>

	<div class="col-xs-8">
	{% for q in recent_questions %}
		
		<li>
			<div class="box row">
				<a href="{% url 'quailapp:social_detail' q.id %}" class="question-box">
					<div class="col-xs-1">
						{% buttons %}
						<div class="btn-group-vertical btn-group-sm" role="group">
							<button class="btn btn-link disabled" name="vote" id="upvote">
								{% bootstrap_icon "chevron-up" %}
							</button>
							<div class="centered votes">{{ q.votes }}</div>
							<button class="btn btn-link disabled" name="vote" id="downvote">
								{% bootstrap_icon "chevron-down" %}
							</button>
						</div>
						{% endbuttons %}
					</div>
					<div class="col-xs-10">
						<p class="question">
							{{ q.text }}<br>
							<span class="unemph">{{ q.created_on }}</span>
						</p>
					</div>
					<div class="col-xs-1">
						<form action="{% url 'quailapp:delete_from_userinfo' q.id %}" method="POST">
							{% csrf_token %}
								<button type="submit" class="btn btn-link btn-link-red right">
									{% bootstrap_icon "remove" %}
								</button>
						</form>
					</div>
				</a>
			</div>
		</li>
	
	{% endfor %}
	</div>
</div>

{% endblock %}

quailapp/templates/quailapp/user_feedback.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block classes %}
{% for course in courses %}
<li>
	<a href="{% url 'quailapp:coursepage_live' course.id %}">{{ course }}</a>
</li>
{% endfor %}
{% endblock %}

{% block social %}
{% for category in categories %}
<li>
	<a href="{% url 'quailapp:social_category' category.id %}">{{ category }}</a>
</li>
{% endfor %}
{% endblock %}

{% block content %}
<a href="{% url 'quailapp:coursepage_live' course.id %}">
{% bootstrap_icon "arrow-left"%} {{course}}
</a>


<h3>Feedback for {{course.last_lecture}}</h3>
{% if provided_feedback %}
<h5>You have already provided feedback for the last lecture, thank you!</h5>
<br>
{% else %}
On a scale of 1-5, how clear / helpful was lecture?
<form action="{% url 'quailapp:user_feedback' course.id %}" method="post">
    {% csrf_token %}
    <div class="form-group radio-group">
      	<label for="id_feedback_choice_0">
      		<input class="" id="id_feedback_choice_0" name="feedback_choice" title="" type="radio" value="1" required>
      		1
      	</label>
		<label for="id_feedback_choice_1">
			<input class="" id="id_feedback_choice_1" name="feedback_choice" title="" type="radio" value="2" required>
			2
		</label>
		<label for="id_feedback_choice_2">
			<input class="" id="id_feedback_choice_2" name="feedback_choice" title="" type="radio" value="3" required>
			3
		</label>
		<label for="id_feedback_choice_3">
			<input class="" id="id_feedback_choice_3" name="feedback_choice" title="" type="radio" value="4" required>
			4
		</label>
		<label for="id_feedback_choice_4">
			<input class="" id="id_feedback_choice_4" name="feedback_choice" title="" type="radio" value="5" required>
			5
		</label>
	</div>
	<div class="form-group">
		<input class="form-control" id="id_your_feedback" maxlength="200" name="your_feedback" placeholder="Your feedback" title="" type="text">
	</div>
    <span class="input-group-btn">
		{% buttons %}
        	<button class="btn btn-secondary{% if provided_feedback %} disabled{% endif %}" type="submit" value="Unregister" onclick="this.disabled=true,this.form.submit();">Submit</button>
		{% endbuttons %}
    </span>
</form>
{% endif %}

<h4>Your past feedback given for {{ course }}</h4>
<ul>
{% for feedback in user_feedback %}
	<li>
		<div class="box-static-blue row">
			<div class="col-xs-1">
				<span>
				{% if not feedback.feedback_choice %}N/A{%else %}{{ feedback.feedback_choice }}/5{% endif %}
				</span>
			</div>
			<div class="col-xs-10">
				<span>
					{% if not feedback.text %}N/A{%else %}{{ feedback }}{% endif %}
				</span>
				<br>
				<span class="unemph">Submitted on: {{ feedback.created_on }}
						for lecture on {{ feedback.lecture_date }}
				</span>
			</div>
			<div class="col-xs-1">
				<form action="{% url 'quailapp:delete_feedback' feedback.id %}" method="POST">
				{% csrf_token %}
					<button type="submit" class="btn btn-link btn-link-red">
					{% bootstrap_icon "remove" %}
				</button>
				</form>
			</div>
		</div>
	</li>
{% endfor %}
</ul>
{% endblock %}