apps/urls.py
from django.conf.urls import include, url
from django.contrib import admin    # enable admin for Django
admin.autodiscover()
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
   url(r'', include('quailapp.urls', namespace="quailapp")),    # allow for more intuitive access to urls in templates
   url(r'^admin/', include(admin.site.urls)),   # include admin link for Django
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

quailapp/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required

from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^index$', login_required(views.index), name='index'),
    #url(r'^get$', login_required(views.get_question), name='get'), # deprecated
    url(r'^(?P<answer_id>[a-zA-Z0-9]+)/deleteans/$', login_required(views.delete_answer), name='deleteans'), # deletes answers assoc w/ question
    url(r'^(?P<question_id>[0-9][a-zA-Z0-9]+)/$', login_required(views.question_detail), name='detail'), # messy solution; question ids too long
    url(r'^(?P<question_id>[a-zA-Z0-9]+)/vote/$', login_required(views.vote), name='vote'), # vote for a specific question
    url(r'^(?P<question_id>[a-zA-Z0-9]+)/star/$', login_required(views.star), name='star'), # star a specific question
    url(r'^(?P<question_id>[a-zA-Z0-9]+)/pin/$', login_required(views.pin), name='pin'), # pin a specific question
    url(r'^(?P<question_id>[a-zA-Z0-9]+)/answer/$', login_required(views.get_answer), name='answer'), # answer a specific question
    url(r'^login$', views.login_CAS, name='login'),
    url(r'^logout$', views.logout_CAS, name='logout'),
    url(r'^(?P<netid>[a-zA-Z0-9]+)/create$', views.create_account, name='create'),
    url(r'^userinfo$', login_required(views.user_info), name='userinfo'),
    url(r'^enroll$', login_required(views.enroll), name='enroll'),
    #url(r'^(?P<course_id>[a-zA-Z0-9]+)/coursepage/$', login_required(views.coursepage), name='coursepage'),
    url(r'^(?P<course_id>[a-zA-Z0-9]+)/coursepage_live/$', login_required(views.coursepage_live), name='coursepage_live'),
    url(r'^(?P<course_id>[a-zA-Z0-9]+)/coursepage_archive/$', login_required(views.coursepage_archive), name='coursepage_archive'),
    url(r'^(?P<question_id>[a-zA-Z0-9]+)/delete_from_coursepage/$', login_required(views.delete_from_coursepage), name='delete_from_coursepage'), # a little hacky.
    url(r'^(?P<tag_id>[a-zA-Z0-9]+)/delete_tag_from_coursepage/$', login_required(views.delete_tag_from_coursepage), name='delete_tag_from_coursepage'), # a little hacky.
    url(r'^(?P<question_id>[a-zA-Z0-9]+)/delete_from_info/$', login_required(views.delete_from_userinfo), name='delete_from_userinfo'),
    url(r'^similar_question$', login_required(views.similar_question), name='similar_question'),
    url(r'^change_name$', login_required(views.change_name), name='change_name'),
    url(r'^(?P<question_id>[a-zA-Z0-9]+)/edit_question/$', login_required(views.edit_question), name='edit_question'),
    url(r'^(?P<question_id>[a-zA-Z0-9]+)/edit_answer/$', login_required(views.edit_answer), name='edit_answer'),
    url(r'^(?P<course_id>[a-zA-Z0-9]+)/answered_questions/$', login_required(views.answered_questions), name='answered_questions'),
    url(r'^(?P<category_id>[a-zA-Z0-9]+)/answered_questions_social/$', login_required(views.answered_questions_social), name='answered_questions_social'),
    url(r'^(?P<course_id>[a-zA-Z0-9]+)/feedback/$', login_required(views.user_feedback), name='user_feedback'),
    url(r'^(?P<feedback_id>[a-zA-Z0-9]+)/feedback/delete$', login_required(views.delete_feedback), name='delete_feedback'),
    url(r'^archived_feedback$', login_required(views.archived_feedback), name='archived_feedback'),
    url(r'^social$', login_required(views.social_home), name='social_home'),
    url(r'^(?P<category_id>[a-zA-Z0-9]+)/social/$', login_required(views.social_category), name='social_category'),
    url(r'^(?P<question_id>[0-9][a-zA-Z0-9]+)/social$', login_required(views.social_detail), name='social_detail'), # messy solution; there CANNOT be a trailing slash, otherwise will confuse w/ social category link
    url(r'^(?P<question_id>[a-zA-Z0-9]+)/delete_from_social/$', login_required(views.delete_from_social), name='delete_from_social'), # a little hacky.
    url(r'^(?P<tag_id>[a-zA-Z0-9]+)/delete_tag_from_social/$', login_required(views.delete_tag_from_social), name='delete_tag_from_social'), # a little hacky.

    #url(r'^class$', views.register_class, name='class'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

quailapp/forms.py
from django import forms
from .models import Course

FEEDBACK_CHOICES = (
    ('1', '1'),
    ('2', '2'),
    ('3', '3'),
    ('4', '4'),
    ('5', '5'),
)

class QuestionForm(forms.Form):
    def __init__(self, *args, **kwargs):
		self.tags = kwargs.pop('tags')
		super(QuestionForm,self).__init__(*args,**kwargs)
		self.fields['your_question'] = forms.CharField(label='Your question', max_length=100)
		self.fields['tags'] = forms.ModelMultipleChoiceField(widget=forms.CheckboxSelectMultiple(), label='', queryset=self.tags, required=False)

class FeedbackForm(forms.Form):
	feedback_choice = forms.ChoiceField(widget=forms.RadioSelect(), label='', choices=FEEDBACK_CHOICES, required=True)
	your_feedback = forms.CharField(label='Your feedback', max_length=200, required=False)

class AnswerForm(forms.Form):
    your_answer = forms.CharField(label='Your answer', max_length=200)

class CommentForm(forms.Form):
    your_comment = forms.CharField(label='Your answer', max_length=300)

class TagForm(forms.Form):
    your_tag = forms.CharField(label='Your tag', max_length=50)

class RegisterForm(forms.Form):
	first_name = forms.CharField(label='First Name:', max_length=100,
		widget=forms.TextInput(attrs={'placeholder': ''}))
	last_name = forms.CharField(label='Last Name:', max_length=100,
		widget=forms.TextInput(attrs={'placeholder': ''}))
	is_student = forms.TypedChoiceField(label='Are you a student?',
		coerce=lambda x: bool(int(x)), choices=[(0,'Lecturer'), (1,'Student')],
		widget=forms.RadioSelect())

class ClassForm(forms.Form):
	your_class = forms.CharField(label='Register class', max_length=50)
	your_professor = forms.CharField(label='Professor', max_length=50)
	start_time = forms.TimeField(label='Start time')
	end_time = forms.TimeField(label='Start time')

class EnrollForm(forms.Form):

	def __init__(self, *args, **kwargs):
		self.courses_available = kwargs.pop('courses_available')
		super(EnrollForm,self).__init__(*args,**kwargs)
		self.fields['courses'] = forms.ModelMultipleChoiceField(widget=forms.CheckboxSelectMultiple(), label='', queryset=self.courses_available)

quailapp/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.core.urlresolvers import reverse
from django.core.exceptions import ObjectDoesNotExist
from django.template import loader
from django.views import generic
from django.utils import timezone
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.contrib import messages
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer

from django.contrib.auth import login, logout, authenticate
#from .custom_auth_backend import QuailCustomBackend

import datetime, re
from datetime import timedelta

import json
from django.core import serializers

from .forms import QuestionForm, AnswerForm, RegisterForm, EnrollForm, CommentForm, TagForm, FeedbackForm
from .models import Question, CASClient, Answer, QuailUser, Course, Comment, Tag, Feedback, AllNetids, ProvidedFeedback, Category

def index(request):
    try:
        user = QuailUser.objects.get(netid=request.user.netid)
    except ObjectDoesNotExist:
        return redirect('/login')
    # course list as query set
    courses = Course.objects.filter(courseid__in=request.user.course_id_list)
    starredQuestions = Question.objects.filter(users_starred__contains=user.netid)

    if request.method == 'POST':
        feedback_id = request.POST['feedback']
        feedback = Feedback.objects.get(pk=feedback_id)
        feedback.is_live = False
        feedback.save()
        return HttpResponseRedirect(reverse('quailapp:index'))

    return render(request, 'quailapp/index.html', {'user':user, 'courses':courses, 'starred_questions':starredQuestions,
        'categories': Category.objects.all()})

# handles what happens when a user uses the vote form on a question
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        vote = request.POST['vote']
    except (KeyError, Question.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'quailapp/index.html', {
            'error_message': "You didn't select a vote.",
            })
    else:
        # if user is upvoting
        if (int(vote) == 1) and ((not question.users_upvoted) or (request.user.netid not in question.users_upvoted)): 
            if question.users_downvoted and request.user.netid in question.users_downvoted:
                users_downvoted = question.users_downvoted.replace("|"+request.user.netid, "")
                question.users_downvoted = users_downvoted
            else:
                users_upvoted = question.users_upvoted + '|' + request.user.netid
                question.users_upvoted = users_upvoted
            question.votes += int(vote)
        
        # if user is downvoting
        elif (int(vote) == -1) and ((not question.users_downvoted) or (request.user.netid not in question.users_downvoted)):
            # if user already upvoted and wants to downvote
            if question.users_upvoted and request.user.netid in question.users_upvoted:
                users_upvoted = question.users_upvoted.replace("|"+request.user.netid, "")
                question.users_upvoted = users_upvoted
            else:
                users_downvoted = question.users_downvoted + '|' + request.user.netid
                question.users_downvoted = users_downvoted
            question.votes += int(vote)
        

        # if not question.users_voted:
        #     question.users_voted = request.user.netid
        #     question.votes += int(vote)
        # elif not request.user.netid in question.users_voted:
        #     question.votes += int(vote)
        #     users_voted = question.users_voted + '|' + request.user.netid
        #     question.users_voted = users_voted

        if (question.votes < -10):  # deletes question if it's downvoted to oblivion
            question.delete()
        else:
            question.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
    
    return HttpResponse(question.votes)
    #return HttpResponseRedirect(reverse('quailapp:coursepage', args=(question.course.id,)))

# handles what happens when a user stars a question
def star(request, question_id):
    if request.is_ajax():
        question = get_object_or_404(Question, pk=question_id)
        star = request.POST['star']
        
        if question.users_starred and request.user.netid in question.users_starred:
            users_starred = question.users_starred.replace("|"+request.user.netid, "")
        else:
            users_starred = question.users_starred + '|' + request.user.netid
        
        question.stars += int(star)
        question.users_starred = users_starred    
        question.save()
        
        return HttpResponse(question.stars)

# handles what happens when someone pins a question to the coursepage
def pin(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    is_pinned = int(request.POST['pin'])
    if (is_pinned == 1):
        question.is_pinned = True
    else:
        question.is_pinned = False
    question.save()
    return HttpResponse("success")
    
    # if (question.is_live == True):
    #     return HttpResponseRedirect(reverse('quailapp:coursepage_live', args=(question.course.id,)))
    # else:
    #     return HttpResponseRedirect(reverse('quailapp:coursepage_archive', args=(question.course.id,)))

def coursepage_live(request, course_id):

    course = get_object_or_404(Course, pk=course_id)    
    # check if course is live
    user = request.user
    now = datetime.datetime.now()
    course_id_list = user.courses_by_id.split('|')

    feedback_exists = user.providedfeedback_set.filter(course=course).exists()
    if feedback_exists:
        feedback_for_course = user.providedfeedback_set.all().get(course=course)
    else:
        return HttpResponse("You are not enrolled in this course")

    # check if all the question ids in the tags are valid
    for tag in course.tag_set.all():
        questions = tag.questions.split('|')
        for q in questions:
            if q != '':
                question_exists = Question.objects.filter(pk=q).exists()
                if not question_exists:
                    t_questions = tag.questions.replace("|"+q, "")
                    tag.questions = t_questions
                    tag.save()

    # check if all the tag ids in the questions are valid
    for question in course.question_set.all():
        tags = question.tags.split('|')
        for t in tags:
            if t != '':
                tag_exists = Tag.objects.filter(pk=t).exists()
                if not tag_exists:
                    q_tags = question.tags.replace("|"+t, "")
                    question.tags = q_tags
                    question.save()

    display_feedback = True

    to_archive = False
    live_month = False
    live_day = False
    live_time = False
    days = course.days

    diff_days = 0
    diff_weeks = 0
    if (now.month >= 1 and now.month < 6):
        live_month = True
    if (re.search(str(now.weekday()), days)):
        live_day = True
    if (now.time() < course.endtime and now.time() > course.starttime):
        live_time = True
    if (live_month and live_day and live_time):
        lecture_date = now.date()
        # update the provided feedback to False with new lecture
        feedback_for_course.provided_feedback = False
        feedback_for_course.save()
        display_feedback = False
        if (course.archive_type == 'every_other_lecture'):
            weekday = now.weekday()
            if (len(days) < 2):
                diff_days = 0
                diff_weeks = 1   # default to archiving every other week if lecture is once a week
            else:
                for i in range(len(days)):
                    if (weekday == int(days[i])):
                        index = i
                diff_days = (weekday - int(days[index-1])) % 7
                diff_weeks = 0
            time_buffer = now - datetime.timedelta(hours=3,days=diff_days, weeks=diff_weeks)
            to_archive = True
        elif (course.archive_type == 'every_lecture'):
            time_buffer = now - datetime.timedelta(hours=3)
            to_archive = True
    else:
        # find out when the last lecture was
        last_lecture = -1
        int_days = [-1] # buffer for the first day
        for day in days:
            int_days.append(int(day))
        int_days.append(10) # a buffer for the last day
        for i in range(len(int_days)-1):
            if now.weekday() == int_days[i]:
                if now.time() < course.starttime:
                    if len(days) == 1:
                        last_lecture = -1
                    else:
                        if i == 1:
                            last_lecture = int_days[i-3]
                        else:
                            last_lecture = int_days[i-1]
                else:
                    last_lecture = int_days[i]
                break
            elif now.weekday() > int_days[i] and now.weekday() < int_days[i+1]:
                if i == 0:
                    last_lecture = int_days[i-2]
                    break
                else:
                    last_lecture = int_days[i]
                    break
        diff = (now.weekday() - last_lecture) % 7
        # if the class only meets once a week, default to the last week's lecture
        if last_lecture == -1:
            diff = 7
        lecture_date = (now - datetime.timedelta(days=diff)).date()
    
    # save the last lecture date to the course
    course.last_lecture = lecture_date
    course.save()

    # check if the user has any feedback before the last lecture
    if (len(user.feedback_set.filter(course=course, lecture_date__gte=lecture_date)) > 0):

quailapp/templates/base.html
{% load staticfiles %}
{% load bootstrap3 %}
{% bootstrap_css %}

<html lang="en">
<head>
	<title>quail</title>
	<link rel="icon" href="{% static "quailapp/logo-black.ico" %}" type="image/x-icon" />
    <link rel="stylesheet" type="text/css" href="{% static "quailapp/style.css" %}" />
    <link href='https://fonts.googleapis.com/css?family=Lato:700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Fira+Sans:300' rel='stylesheet' type='text/css'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
</head>

<body>
	<script>
    $(document).ready(function() {
        $('a[href="' + this.location.pathname + '"]').parent().addClass('active');
    });
	</script>
	<div class="row">
  		<div class="col-sm-2">
    		<div class="sidebar-nav">
			<nav class="navbar navbar-inverse navbar-simple">
				<div class="container-fluid">
					<div class="navbar-header">
						<a class="navbar-brand" href="{% url 'quailapp:home' %}">
							<p><img class="xs" src="{% static "quailapp/logo.png" %}"> quail</p>
						</a>
					</div>
					<br>
					<div class="navbar-collapse collapse sidebar-navbar-collapse">
						<ul class="nav navbar-nav">
							<li>
								<a href="{% url 'quailapp:index' %}">{% bootstrap_icon "home" %} Home</a>
							</li>
							<li>
								<a href="{% url 'quailapp:userinfo' %}">{% bootstrap_icon "user" %} User</a>
							</li>
							<li class="dropdown">
			  					<a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
			  						{% bootstrap_icon "book" %} Classes
			  						<span class="caret"></span>
			  					</a>
			  					<ul class="dropdown-menu">
									{% block classes %}{% endblock %}
								</ul>
							</li>
							<li class="dropdown">
								<a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
			  						{% bootstrap_icon "comment" %} Social
			  						<span class="caret"></span>
			  					</a>
			  					<ul class="dropdown-menu">
			  						<li>
			  							<a href="{% url 'quailapp:social_home' %}"> All</a>
			  						</li>
									{% block social %}{% endblock %}
								</ul>
							</li>
							<li><a href="{% url 'quailapp:logout' %}">{% bootstrap_icon "lock" %} Logout</a></li>
						</ul>
					</div>
				</nav>
			</div>
		</div>
		<div class="col-sm-10">
			<div id="content">
	        {% block content %}{% endblock %}
	    	</div>
    	</div>
	</div>
</body>
</html>

quailapp/templates/basedark.html
{% load staticfiles %}
{% load bootstrap3 %}
{% bootstrap_css %}

<html lang="en">
<head>
	<title>quail</title>
	<link rel="icon" href="{% static "quailapp/logo-black.ico" %}" type="image/x-icon" />
    <link rel="stylesheet" type="text/css" href="{% static "quailapp/style.css" %}" />
    <link href='https://fonts.googleapis.com/css?family=Lato:700' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Fira+Sans:300' rel='stylesheet' type='text/css'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
</head>

<body class="dark">
	<script>
    $(document).ready(function() {
        $('a[href="' + this.location.pathname + '"]').parent().addClass('active');
    });
	</script>
<div class="row">
  		<div class="col-sm-2">
    		<div class="sidebar-nav">
			<nav class="navbar navbar-inverse navbar-simple">
				<div class="container-fluid">
					<div class="navbar-header">
						<a class="navbar-brand" href="{% url 'quailapp:home' %}">
							<p><img class="xs" src="{% static "quailapp/logo.png" %}"> quail</p>
						</a>
					</div>
					<br>
					<div class="navbar-collapse collapse sidebar-navbar-collapse">
						<ul class="nav navbar-nav">
							<li><a href="{% url 'quailapp:index' %}">{% bootstrap_icon "home" %} Home</a></li>
							<li><a href="{% url 'quailapp:userinfo' %}">{% bootstrap_icon "user" %} User</a></li>
							<li class="dropdown">
			  					<a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
			  						{% bootstrap_icon "book" %} Classes
			  						<span class="caret"></span>
			  					</a>
			  					<ul class="dropdown-menu">
									{% block classes %}{% endblock %}
								</ul>
							</li>
							<li class="dropdown">
								<a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
			  						{% bootstrap_icon "comment" %} Social
			  						<span class="caret"></span>
			  					</a>
			  					<ul class="dropdown-menu">
			  						<li>
			  							<a href="{% url 'quailapp:social_home' %}"> All</a>
			  						</li>
									{% block social %}{% endblock %}
								</ul>
							</li>
							<li><a href="{% url 'quailapp:logout' %}">{% bootstrap_icon "lock" %} Logout</a></li>
						</ul>
					</div>
				</nav>
			</div>
		</div>
		<div class="col-sm-10">
			<div id="content">
	        {% block content %}{% endblock %}
	    	</div>
    	</div>
	</div>
</body>
</html>